# Generated by Django 5.2.7 on 2025-10-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_about_education_experience_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('user', 'school_name', 'field_name', 'start_year', 'end_year')},
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('user', 'company_name', 'position_name', 'start_year', 'end_year', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'project_name')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('user', 'skill_name')},
        ),
    ]
