# Generated by Django 5.2.7 on 2025-10-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_googleuser_user_name_googleuser_user_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='job_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
