# Generated by Django 5.2.7 on 2025-11-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_googleuser_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter')], default='candidate', max_length=10),
        ),
    ]
