# Generated by Django 5.2.7 on 2025-11-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
