# Generated by Django 5.2.7 on 2025-11-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='tips',
            field=models.TextField(blank=True),
        ),
    ]
