# Generated by Django 5.2.7 on 2025-11-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_resume_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='tips',
        ),
    ]
