# Generated by Django 5.2.7 on 2025-11-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_Account', '0002_rename_salary_job_experience_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='about_job',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='key_responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
