# Generated by Django 5.2.7 on 2025-11-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_Account', '0004_jobapplication_delete_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
    ]
